import { SpecialItem } from '../types';

export const MOCK_SPECIALS: SpecialItem[] = [
  { id: '1', name: 'Organic Hass Avocados', originalPrice: 2.50, salePrice: 1.25, category: 'Produce', description: 'Creamy, nutrient-dense avocados perfect for toast or guacamole.' },
  { id: '2', name: 'Fresh Atlantic Salmon Fillet', originalPrice: 15.99, salePrice: 10.99, category: 'Meat & Seafood', description: 'Rich in Omega-3, this salmon is perfect for pan-searing or grilling.' },
  { id: '3', name: 'Zucchini (Green)', originalPrice: 1.20, salePrice: 0.80, category: 'Produce', description: 'Versatile summer squash that can be spiraled into noodles or roasted.' },
  { id: '4', name: 'Extra Virgin Olive Oil (500ml)', originalPrice: 12.00, salePrice: 8.50, category: 'Pantry', description: 'Cold-pressed oil with a robust flavor, ideal for dressings and low-heat cooking.' },
  { id: '5', name: 'Greek Yogurt (Plain, 1kg)', originalPrice: 6.50, salePrice: 4.00, category: 'Dairy & Eggs', description: 'Thick, tangy yogurt high in protein and great for breakfast or as a sour cream sub.' },
  { id: '6', name: 'Free-Range Large Eggs (12pk)', originalPrice: 5.50, salePrice: 3.99, category: 'Dairy & Eggs', description: 'Farm-fresh eggs from chickens that roam freely. Essential for any kitchen.' },
  { id: '7', name: 'Grass-Fed Ribeye Steak', originalPrice: 22.00, salePrice: 16.50, category: 'Meat & Seafood', description: 'Well-marbled steak with exceptional flavor from pasture-raised cattle.' },
  { id: '8', name: 'Sweet Potatoes', originalPrice: 1.80, salePrice: 1.10, category: 'Produce', description: 'Starchy and sweet root vegetable, excellent roasted or mashed.' },
  { id: '9', name: 'Sourdough Loaf', originalPrice: 5.50, salePrice: 3.50, category: 'Bakery', description: 'Traditionally fermented bread with a signature tang and chewy crust.' },
  { id: '10', name: 'Organic Baby Spinach (200g)', originalPrice: 4.00, salePrice: 2.75, category: 'Produce', description: 'Tender baby leaves that are nutrient-rich and great for salads or smoothies.' },
  { id: '11', name: 'Cherry Tomatoes', originalPrice: 3.50, salePrice: 2.00, category: 'Produce', description: 'Sweet and juicy bite-sized tomatoes perfect for snacking or roasting.' },
  { id: '12', name: 'Chicken Thighs (Skinless, 500g)', originalPrice: 9.50, salePrice: 6.99, category: 'Meat & Seafood', description: 'Juicy and flavorful chicken thighs, more forgiving than breast when cooking.' },
  { id: '13', name: 'Quinoa (White, 500g)', originalPrice: 7.00, salePrice: 4.50, category: 'Pantry', description: 'Gluten-free ancient grain that provides a complete source of protein.' },
  { id: '14', name: 'Fresh Blueberries (125g)', originalPrice: 4.50, salePrice: 2.99, category: 'Produce', description: 'Antioxidant-rich berries that add a sweet pop to any dish.' },
  { id: '15', name: 'Feta Cheese (200g)', originalPrice: 5.00, salePrice: 3.20, category: 'Dairy & Eggs', description: 'Crumbly, salty cheese made from sheep or goat milk, classic in salads.' },
  { id: '16', name: 'Red Bell Peppers', originalPrice: 1.50, salePrice: 0.95, category: 'Produce', description: 'Sweet and crunchy peppers, high in Vitamin C and great for stir-fries.' },
  { id: '17', name: 'Ground Turkey (500g)', originalPrice: 8.00, salePrice: 5.50, category: 'Meat & Seafood', description: 'Lean alternative to ground beef, perfect for burgers or tacos.' },
  { id: '18', name: 'Basmati Rice (1kg)', originalPrice: 5.00, salePrice: 3.50, category: 'Pantry', description: 'Fragrant long-grain rice that remains fluffy when cooked.' },
  { id: '19', name: 'Unsalted Butter (250g)', originalPrice: 4.50, salePrice: 3.00, category: 'Dairy & Eggs', description: 'Pure cream butter without added salt, essential for baking control.' },
  { id: '20', name: 'Asparagus Bunch', originalPrice: 3.50, salePrice: 1.99, category: 'Produce', description: 'Elegant green spears that are delicious steamed, roasted, or grilled.' },
  { id: '21', name: 'Lemon (Single)', originalPrice: 0.90, salePrice: 0.50, category: 'Produce', description: 'Essential citrus for adding acidity and brightness to recipes.' },
  { id: '22', name: 'Honey (Pure, 500g)', originalPrice: 9.00, salePrice: 6.50, category: 'Pantry', description: 'Natural sweetener with complex floral notes and antioxidant properties.' },
  { id: '23', name: 'Almond Milk (Unsweetened, 1L)', originalPrice: 4.00, salePrice: 2.50, category: 'Dairy & Eggs', description: 'Nutty and creamy dairy alternative, perfect for smoothies or coffee.' },
  { id: '24', name: 'Chickpeas (Canned, 400g)', originalPrice: 1.50, salePrice: 0.99, category: 'Pantry', description: 'Fiber-rich legumes also known as garbanzo beans, great for hummus.' },
  { id: '25', name: 'Red Onions', originalPrice: 1.20, salePrice: 0.70, category: 'Produce', description: 'Sharp and colorful onions, best used raw in salads or pickled.' },
  { id: '26', name: 'Cantaloupe / Rockmelon', originalPrice: 5.00, salePrice: 3.00, category: 'Produce', description: 'Refreshing orange-fleshed melon with a sweet and musky aroma.' },
  { id: '27', name: 'Whole Chicken', originalPrice: 12.00, salePrice: 8.99, category: 'Meat & Seafood', description: 'Perfect for Sunday roasts, providing meat for multiple meals and stock.' },
  { id: '28', name: 'Ciabatta Rolls (4pk)', originalPrice: 4.00, salePrice: 2.50, category: 'Bakery', description: 'Italian-style rolls with a porous texture and crisp crust.' },
  { id: '29', name: 'English Muffins', originalPrice: 3.50, salePrice: 2.25, category: 'Bakery', description: 'Fork-split rounds with nooks and crannies perfect for holding butter.' },
  { id: '30', name: 'Frozen Peas (500g)', originalPrice: 2.50, salePrice: 1.50, category: 'Pantry', description: 'Sweet peas picked at peak ripeness and frozen to lock in nutrients.' },
  { id: '31', name: 'Garlic (3pk)', originalPrice: 2.50, salePrice: 1.50, category: 'Produce', description: 'Aromatic bulb essential for building deep flavor in savory dishes.' },
  { id: '32', name: 'Fresh Cilantro / Coriander', originalPrice: 2.00, salePrice: 1.00, category: 'Produce', description: 'Bright, herbaceous green perfect for garnishing Mexican or Asian dishes.' },
  { id: '33', name: 'Black Beans (Canned, 400g)', originalPrice: 1.50, salePrice: 0.99, category: 'Pantry', description: 'Protein-packed beans commonly used in Latin American cuisine.' },
  { id: '34', name: 'Mozzarella Ball (Fresh)', originalPrice: 5.50, salePrice: 3.99, category: 'Dairy & Eggs', description: 'Soft, milky cheese that is a must for pizza or Caprese salads.' },
  { id: '35', name: 'Lamb Cutlets (4pk)', originalPrice: 18.00, salePrice: 13.50, category: 'Meat & Seafood', description: 'Tender and sweet lamb chops, best cooked quickly over high heat.' },
  { id: '36', name: 'Kale (Bunch)', originalPrice: 3.00, salePrice: 1.75, category: 'Produce', description: 'Hearty, fibrous green that is excellent in soups or as massaged salad.' },
  { id: '37', name: 'Whole Wheat Pasta (500g)', originalPrice: 3.50, salePrice: 2.20, category: 'Pantry', description: 'Fiber-rich pasta that provides a nutty flavor and more nutrition.' },
  { id: '38', name: 'Swiss Cheese Slices (200g)', originalPrice: 4.50, salePrice: 3.00, category: 'Dairy & Eggs', description: 'Mild and nutty cheese with iconic holes, great for melting in sandwiches.' },
  { id: '39', name: 'Balsamic Glaze (250ml)', originalPrice: 6.00, salePrice: 4.00, category: 'Pantry', description: 'Reduced balsamic vinegar with a syrupy consistency and sweet-tart flavor.' },
  { id: '40', name: 'Pine Nuts (50g)', originalPrice: 7.00, salePrice: 4.99, category: 'Pantry', description: 'Rich and buttery seeds essential for pesto or adding crunch to salads.' },
];

export const getSpecials = () => Promise.resolve(MOCK_SPECIALS);
