import { SpecialItem } from '../types';

export const MOCK_SPECIALS: SpecialItem[] = [
  { id: '1', name: 'Organic Hass Avocados', originalPrice: 2.50, salePrice: 1.25, category: 'Produce' },
  { id: '2', name: 'Fresh Atlantic Salmon Fillet', originalPrice: 15.99, salePrice: 10.99, category: 'Meat & Seafood' },
  { id: '3', name: 'Zucchini (Green)', originalPrice: 1.20, salePrice: 0.80, category: 'Produce' },
  { id: '4', name: 'Extra Virgin Olive Oil (500ml)', originalPrice: 12.00, salePrice: 8.50, category: 'Pantry' },
  { id: '5', name: 'Greek Yogurt (Plain, 1kg)', originalPrice: 6.50, salePrice: 4.00, category: 'Dairy & Eggs' },
  { id: '6', name: 'Free-Range Large Eggs (12pk)', originalPrice: 5.50, salePrice: 3.99, category: 'Dairy & Eggs' },
  { id: '7', name: 'Grass-Fed Ribeye Steak', originalPrice: 22.00, salePrice: 16.50, category: 'Meat & Seafood' },
  { id: '8', name: 'Sweet Potatoes', originalPrice: 1.80, salePrice: 1.10, category: 'Produce' },
  { id: '9', name: 'Sourdough Loaf', originalPrice: 5.50, salePrice: 3.50, category: 'Bakery' },
  { id: '10', name: 'Organic Baby Spinach (200g)', originalPrice: 4.00, salePrice: 2.75, category: 'Produce' },
  { id: '11', name: 'Cherry Tomatoes', originalPrice: 3.50, salePrice: 2.00, category: 'Produce' },
  { id: '12', name: 'Chicken Thighs (Skinless, 500g)', originalPrice: 9.50, salePrice: 6.99, category: 'Meat & Seafood' },
  { id: '13', name: 'Quinoa (White, 500g)', originalPrice: 7.00, salePrice: 4.50, category: 'Pantry' },
  { id: '14', name: 'Fresh Blueberries (125g)', originalPrice: 4.50, salePrice: 2.99, category: 'Produce' },
  { id: '15', name: 'Feta Cheese (200g)', originalPrice: 5.00, salePrice: 3.20, category: 'Dairy & Eggs' },
  { id: '16', name: 'Red Bell Peppers', originalPrice: 1.50, salePrice: 0.95, category: 'Produce' },
  { id: '17', name: 'Ground Turkey (500g)', originalPrice: 8.00, salePrice: 5.50, category: 'Meat & Seafood' },
  { id: '18', name: 'Basmati Rice (1kg)', originalPrice: 5.00, salePrice: 3.50, category: 'Pantry' },
  { id: '19', name: 'Unsalted Butter (250g)', originalPrice: 4.50, salePrice: 3.00, category: 'Dairy & Eggs' },
  { id: '20', name: 'Asparagus Bunch', originalPrice: 3.50, salePrice: 1.99, category: 'Produce' },
  { id: '21', name: 'Lemon (Single)', originalPrice: 0.90, salePrice: 0.50, category: 'Produce' },
  { id: '22', name: 'Honey (Pure, 500g)', originalPrice: 9.00, salePrice: 6.50, category: 'Pantry' },
  { id: '23', name: 'Almond Milk (Unsweetened, 1L)', originalPrice: 4.00, salePrice: 2.50, category: 'Dairy & Eggs' },
  { id: '24', name: 'Chickpeas (Canned, 400g)', originalPrice: 1.50, salePrice: 0.99, category: 'Pantry' },
  { id: '25', name: 'Red Onions', originalPrice: 1.20, salePrice: 0.70, category: 'Produce' },
  { id: '26', name: 'Cantaloupe / Rockmelon', originalPrice: 5.00, salePrice: 3.00, category: 'Produce' },
  { id: '27', name: 'Whole Chicken', originalPrice: 12.00, salePrice: 8.99, category: 'Meat & Seafood' },
  { id: '28', name: 'Ciabatta Rolls (4pk)', originalPrice: 4.00, salePrice: 2.50, category: 'Bakery' },
  { id: '29', name: 'English Muffins', originalPrice: 3.50, salePrice: 2.25, category: 'Bakery' },
  { id: '30', name: 'Frozen Peas (500g)', originalPrice: 2.50, salePrice: 1.50, category: 'Pantry' },
  { id: '31', name: 'Garlic (3pk)', originalPrice: 2.50, salePrice: 1.50, category: 'Produce' },
  { id: '32', name: 'Fresh Cilantro / Coriander', originalPrice: 2.00, salePrice: 1.00, category: 'Produce' },
  { id: '33', name: 'Black Beans (Canned, 400g)', originalPrice: 1.50, salePrice: 0.99, category: 'Pantry' },
  { id: '34', name: 'Mozzarella Ball (Fresh)', originalPrice: 5.50, salePrice: 3.99, category: 'Dairy & Eggs' },
  { id: '35', name: 'Lamb Cutlets (4pk)', originalPrice: 18.00, salePrice: 13.50, category: 'Meat & Seafood' },
  { id: '36', name: 'Kale (Bunch)', originalPrice: 3.00, salePrice: 1.75, category: 'Produce' },
  { id: '37', name: 'Whole Wheat Pasta (500g)', originalPrice: 3.50, salePrice: 2.20, category: 'Pantry' },
  { id: '38', name: 'Swiss Cheese Slices (200g)', originalPrice: 4.50, salePrice: 3.00, category: 'Dairy & Eggs' },
  { id: '39', name: 'Balsamic Glaze (250ml)', originalPrice: 6.00, salePrice: 4.00, category: 'Pantry' },
  { id: '40', name: 'Pine Nuts (50g)', originalPrice: 7.00, salePrice: 4.99, category: 'Pantry' },
];

export const getSpecials = () => Promise.resolve(MOCK_SPECIALS);
